display: add dummy libsdedrm blueprint
to satisfy ELF

error: vendor/qcom/common/vendor/display/5.15/Android.bp:448:1: "libsdmextension" depends on undefined module "libsdedrm".
Module "libsdmextension" is defined in namespace "vendor/qcom/common/vendor/display/5.15"

Change-Id: I0d075cf0a96e9de1f4f9fcbf2163c1e68b8572fd