Fix module display_intf_headers dependency on other namespace vendor/qcom/sm8150
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l
out/.module_paths/Android.bp.list -b out/soong -n out -d
out/soong/build.ninja.d -o out/soong/build.ninja Android.bp
error: hardware/qcom/sm8150/display/Android.bp:22:1: "display_headers"
depends on undefined module "display_intf_headers"
Module "display_headers" is defined in namespace
"hardware/qcom/sm8150/display" which can read these 2 namespaces:
["hardware/qcom/sm8150/display" "."]
Module "display_intf_headers" can be found in these namespaces:
["vendor/qcom/sm8150"]

Bug: 117197316
Change-Id: Id142e3dbe202bd743be946fddde697ec090440a8