Revert "display: msm8994: format fixes"
This reverts commit 9b17141761ef44010e2798504da66d8e19970256.

Revert fixes errors during compiling:
error: format specifies type 'long' but the argument has type 'ssize_t' (aka 'int') [-Werror,-Wformat]

Change-Id: I62f6ea25073747025440912652f12a7fc5052f6b