[DNM] Revert "gralloc: Fix issue with mmap/munmap meta due to reserved size"
 * display/gralloc/gr_buf_mgr.cpp: error: no member named 'reserved_size'

This reverts commit 45f98c2ec9028b52ae043746811105af9779d079.

Change-Id: I7b552bf1958eedd6dcb04a1bbdd3063a9b81cda4