Revert "display: Remove unused headers"
This reverts commit 7e14ffc7347b699dcda64371b1284ef392b68797.

Fix:
hardware/qcom/sm8150/display/sdm/include/core/layer_buffer.h:33:10:
fatal error: 'color_metadata.h' file not found
hardware/qcom/sm8150/display/gpu_tonemapper/EGLImageBuffer.h:24:10:
fatal error: 'gralloc_priv.h' file not found

Bug: 117817875
Bug: 128639903
Change-Id: I1a99c13ef715f05308fcdc875bffadac51dfcf42